"use client";

import { useState } from "react";
import { Download, FileText, Table } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Widget } from "@/components/widgets/Widget";
import { WidgetHeader } from "@/components/widgets/WidgetHeader";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { cn } from "@/lib/utils";

interface ExportReportProps {
  data: {
    openPRs?: number;
    openIssues?: number;
    openBugs?: number;
    criticalCount?: number;
    incidentCount?: number;
    paymentSuccessRate?: number | null;
    fraudRate?: number | null;
    uptime?: number | null;
  };
  filters?: {
    dateRange?: string;
    squad?: string;
    environment?: string;
  };
  className?: string;
}

export function ExportReport({ data, filters, className }: ExportReportProps) {
  const [open, setOpen] = useState(false);
  const [format, setFormat] = useState<"markdown" | "csv">("markdown");
  const [copied, setCopied] = useState(false);

  const date = new Date().toLocaleDateString();
  const filterLine = `Filters: ${filters?.dateRange || "7d"} · Squad: ${filters?.squad || "all"} · Env: ${filters?.environment || "all"}`;

  const markdown = [
    `# CTO Dashboard Summary — ${date}`,
    "",
    filterLine,
    "",
    "## Key signals",
    "",
    `- **Open PRs:** ${data.openPRs ?? "—"}`,
    `- **Open Issues:** ${data.openIssues ?? "—"}`,
    `- **Open Bugs:** ${data.openBugs ?? "—"}`,
    `- **Critical CVEs:** ${data.criticalCount ?? "—"}`,
    `- **Active Incidents:** ${data.incidentCount ?? "—"}`,
    `- **Payment Success:** ${data.paymentSuccessRate != null ? `${data.paymentSuccessRate.toFixed(2)}%` : "—"}`,
    `- **Fraud Rate:** ${data.fraudRate != null ? `${data.fraudRate.toFixed(2)}%` : "—"}`,
    `- **Uptime:** ${data.uptime != null ? `${data.uptime.toFixed(2)}%` : "—"}`,
    "",
    "_Generated by CTO Dash_",
  ].join("\n");

  const csv = [
    "Metric,Value",
    `Open PRs,${data.openPRs ?? ""}`,
    `Open Issues,${data.openIssues ?? ""}`,
    `Open Bugs,${data.openBugs ?? ""}`,
    `Critical CVEs,${data.criticalCount ?? ""}`,
    `Active Incidents,${data.incidentCount ?? ""}`,
    `Payment Success,${data.paymentSuccessRate != null ? data.paymentSuccessRate.toFixed(2) + "%" : ""}`,
    `Fraud Rate,${data.fraudRate != null ? data.fraudRate.toFixed(2) + "%" : ""}`,
    `Uptime,${data.uptime != null ? data.uptime.toFixed(2) + "%" : ""}`,
  ].join("\n");

  const content = format === "markdown" ? markdown : csv;
  const filename = `cto-dash-${date}.${format === "markdown" ? "md" : "csv"}`;
  const mime = format === "markdown" ? "text/markdown" : "text/csv";

  function download() {
    const blob = new Blob([content], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  }

  async function copy() {
    await navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  }

  return (
    <>
      <Widget className={className}>
        <WidgetHeader
          title="Export Report"
          subtitle="Download board summary for standups"
          action={
            <Button size="sm" className="gap-2" onClick={() => setOpen(true)}>
              <Download size={14} /> Export
            </Button>
          }
        />
        <div className="flex gap-2">
          <Button variant="outline" size="sm" className="gap-2" onClick={() => setOpen(true)}>
            <FileText size={14} /> Markdown
          </Button>
          <Button variant="outline" size="sm" className="gap-2" onClick={() => { setFormat("csv"); setOpen(true); }}>
            <Table size={14} /> CSV
          </Button>
        </div>
      </Widget>

      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="sm:max-w-lg">
          <DialogHeader>
            <DialogTitle>Export Report</DialogTitle>
            <DialogDescription>
              Download a snapshot of today’s CTO dashboard signals.
            </DialogDescription>
          </DialogHeader>

          <div className="mt-2 flex gap-2">
            <Button
              variant={format === "markdown" ? "default" : "outline"}
              size="sm"
              className="gap-2"
              onClick={() => setFormat("markdown")}
            >
              <FileText size={14} /> Markdown
            </Button>
            <Button
              variant={format === "csv" ? "default" : "outline"}
              size="sm"
              className="gap-2"
              onClick={() => setFormat("csv")}
            >
              <Table size={14} /> CSV
            </Button>
          </div>

          <pre className={cn("mt-4 max-h-72 overflow-auto rounded-lg border bg-muted p-3 text-xs", format === "csv" && "whitespace-pre")}>
            {content}
          </pre>

          <div className="mt-4 flex gap-2">
            <Button className="gap-2" onClick={download}>
              <Download size={14} /> Download
            </Button>
            <Button variant="outline" onClick={copy}>
              {copied ? "Copied!" : "Copy to clipboard"}
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}
